export const storageKeys = {
  authSession: 'chatterly.auth.session',
  currentUser: 'chatterly.user.current',
  contacts: 'chatterly.contacts.cache',
  chats: 'chatterly.chats.cache',
  messagesByChat: 'chatterly.messages.by-chat',
  pendingMessages: 'chatterly.messages.pending',
  searchHistory: 'chatterly.search.history',
  starredMessages: 'chatterly.messages.starred',
  messageReactions: 'chatterly.messages.reactions',
  deletedMessages: 'chatterly.messages.deleted',
  chatPreferences: 'chatterly.chats.preferences',
  unreadCounts: 'chatterly.chats.unread-counts',
  networkMode: 'chatterly.dev.network-mode',
};
